name: Check Suite

on: push

permissions:
  contents: read

jobs:
  common:
    uses: aileron-project/scripts/.github/workflows/check-suite-common.yaml@main
    secrets: inherit

  proto:
    uses: aileron-project/scripts/.github/workflows/check-suite-proto.yaml@main
    secrets: inherit

  go:
    uses: aileron-project/scripts/.github/workflows/check-suite-go.yaml@main
    secrets: inherit
